# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.vr-common-library
canonical: http://hl7.org/fhir/us/vr-common-library
name: VitalRecordsCommonLibrary
title: Vital Records Common Library (VRCL) STU2-ballot
# description: Example Implementation Guide for getting started with SUSHI
status: active # draft | active | retired | unknown
version: 2.0.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 
    version: 5.0.1
    id: hl7fhiruscore
  hl7.fhir.us.odh: 
    version: 1.3.0
    id: odh
  us.nlm.vsac:
    version: 0.17.0
    uri: http://fhir.org/packages/us.nlm.vsac/ImplementationGuide/us.nlm.vsac
    id: usnlmvsac
  us.cdc.phinvads:
    version: 0.12.0
    uri: http://fhir.org/packages/us.cdc.phinvads/ImplementationGuide/us.cdc.phinvads
    id: uscdcphinvads

copyrightYear: 2023+
releaseLabel: trial-use # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0  # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 International / Public Health
  url: http://www.hl7.org/Special/committees/pher
  # email: test@example.org

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#
# dependencies:
#   hl7.fhir.us.core: 3.1.0
#   hl7.fhir.us.mcode:
#     id: mcode
#     uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
#     version: 1.0.0
#
#
# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
#
pages:
  index.md: 
    title: Home
  usage.md:
    title: Usage
  change_log.md:
    title: Change Log 
  the_specification.md:
    title: Specification 
  vr_ig_harmonization.md:
    title: Vital Records FHIR Implementation Guide Harmonization Plan 
  content-transitions.md:
    title: Content Transitions (STU1.1 to STU2 Changes)
  downloads.md:
    title:  Downloads 
  credits.md:
    title: Credits
  



#
#
# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array.
# For parameters defined by core FHIR see:
# http://build.fhir.org/codesystem-guide-parameter-code.html
# For parameters defined by the FHIR Tools IG see:
# http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
#
# parameters:
#   excludettl: true
#   validation: [allow-any-extensions, no-broken-links]
parameters:
  show-inherited-invariants: false
  path-expansion-params: '../../input/_resources/exp-params.json'  # for using US ed of SNOMED
  version-comparison-master: true 
#
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │ The menu property will be used to generate the input/menu.xml file. The menu is represented    │
# │ as a simple structure where the YAML key is the menu item name and the value is the URL.       │
# │ The IG publisher currently only supports one level deep on sub-menus. To provide a             │
# │ custom menu.xml file, do not include this property and include a `menu.xml` file in            │
# │ input/includes. To use a provided input/includes/menu.xml file, delete the "menu"              │
# │ property below.                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: 
    Home: index.html
    Vital Records FHIR IG Harmonization Plan: vr_ig_harmonization.html
    Credits: credits.html
  Implementer Guidance: 
    Specification: the_specification.html
    Usage Notes: usage.html
  Artifacts: artifacts.html
  Changes: 
    Change Log: change_log.html
    Content Transitions: content-transitions.html
  Downloads:  downloads.html
  

# ╭───────────────────────────Less Common Implementation Guide Properties──────────────────────────╮
# │  Uncomment the properties below to configure additional properties on the ImplementationGuide  │
# │  resource. These properties are less commonly needed than those above.                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#
# Those who need more control or want to add additional details to the contact values can use
# contact directly and follow the format outlined in the ImplementationGuide resource and
# ContactDetail.
#
# contact:
#   - name: Bob Smith
#     telecom:
#       - system: email # phone | fax | email | pager | url | sms | other
#         value: bobsmith@example.org
#         use: work
#
#
# The global property corresponds to the IG.global property, but it
# uses the type as the YAML key and the profile as its value. Since
# FHIR does not explicitly disallow more than one profile per type,
# neither do we; the value can be a single profile URL or an array
# of profile URLs. If a value is an id or name, SUSHI will replace
# it with the correct canonical when generating the IG JSON.
#
# global:
#   Patient: http://example.org/fhir/StructureDefinition/my-patient-profile
#   Encounter: http://example.org/fhir/StructureDefinition/my-encounter-profile
#
#
# The resources property corresponds to IG.definition.resource.
# SUSHI can auto-generate all of the resource entries based on
# the FSH definitions and/or information in any user-provided
# JSON or XML resource files. If the generated entries are not
# sufficient or complete, however, the author can add entries
# here. If the reference matches a generated entry, it will
# replace the generated entry. If it doesn't match any generated
# entries, it will be added to the generated entries. The format
# follows IG.definition.resource with the following differences:
#   * use IG.definition.resource.reference.reference as the YAML key.
#   * if the key is an id or name, SUSHI will replace it with the
#     correct URL when generating the IG JSON.
#   * specify "omit" to omit a FSH-generated resource from the
#     resource list.
#   * if the exampleCanonical is an id or name, SUSHI will replace
#     it with the correct canonical when generating the IG JSON.
#   * groupingId can be used, but top-level groups syntax may be a
#     better option (see below).
# The following are simple examples to demonstrate what this might
# look like:
#
# resources:
#   Patient/my-example-patient:
#     name: My Example Patient
#     description: An example Patient
#     exampleBoolean: true
#   Patient/bad-example: omit
#
#
# Groups can control certain aspects of the IG generation.  The IG
# documentation recommends that authors use the default groups that
# are provided by the templating framework, but if authors want to
# use their own instead, they can use the mechanism below.  This will
# create IG.definition.grouping entries and associate the individual
# resource entries with the corresponding groupIds. If a resource
# is specified by id or name, SUSHI will replace it with the correct
# URL when generating the IG JSON.
#

groups:
  PatientProfiles:
    name: People Profiles
    resources:
      - PatientChildVitalRecords
      - PatientMotherVitalRecords
      - PatientVitalRecords
      - PractitionerVitalRecords
      - RelatedPersonFatherNaturalVitalRecords
      - RelatedPersonFatherVitalRecords
      - RelatedPersonMotherVitalRecords
      - RelatedPersonParentVitalRecords
  
  RaceEthnicityProfiles:
    name: Race and Ethnicity Profiles
    resources:
      - ObservationCodedRaceAndEthnicityVitalRecords
      - ObservationInputRaceAndEthnicityVitalRecords

  OtherProfiles:
    name: Other Profiles
    resources:
      - LocationVitalRecords 
      - ObservationAutopsyPerformedIndicatorVitalRecords
      - ObservationEducationLevelVitalRecords
      - ObservationEmergingIssuesVitalRecords
      - ObservationUsualWorkVitalRecords

  AddressExtensions:
    name: Address Extensions
    resources:
      - ExtensionCityCodeVitalRecords
      - ExtensionDistrictCodeVitalRecords
      - ExtensionPostDirectionalVitalRecords
      - ExtensionPreDirectionalVitalRecords
      - ExtensionStreetDesignatorVitalRecords
      - ExtensionStreetNameVitalRecords
      - ExtensionStreetNumberVitalRecords
      - ExtensionUnitOrAptNumberVitalRecords
      - ExtensionWithinCityLimitsIndicatorVitalRecords

  PartialDateTimeExtensions:
    name: Partial Date and Time Extensions
    resources:
      - ExtensionPartialDateTimeVitalRecords
      - ExtensionPartialDateVitalRecords

  RecordIdentifierExtensions:
    name: Record Identifier Extensions 
    resources:
      - AuxiliaryStateIdentifier1
      - AuxiliaryStateIdentifier2
      - CertificateNumber
  
  OtherExtensions:
    name: Other Extensions
    resources:
      - ExtensionPatientFetalDeathVitalRecords
      - ExtensionRelatedpersonBirthplaceVitalRecords
      #- ExtensionRelatedPersonDeceasedVitalRecords
      - ExtensionRoleVitalRecords 
      - ExtensionBypassEditFlagVitalRecords
      - ExtensionReportedParentAgeAtDeliveryVitalRecords
  
  AddressCodeSystems:
    name: Address CodeSystems
    resources:
      #- CodeSystemCanadianProvincesVitalRecords
      - CodeSystemCountryCodeVitalRecords  
      - CodeSystemJurisdictionsVitalRecords
      - CodeSystemUSStatesTerritoriesVitalRecords
      
  EditFlagCodeSystems:
    name: Edit Flag CodeSystems
    resources:
      - CodeSystemEditFlagsVitalRecords

  VRCLCodeSystems:
    name: Other CodeSystems
    resources:
      - CodeSystemComponentVitalRecords
      - CodeSystemHispanicOriginVitalRecords
      - CodeSystemIJEVitalRecords
      - CodeSystemMissingValueReasonVitalRecords
      - CodeSystemRaceCodeVitalRecords
      - CodeSystemRaceRecode40VitalRecords
      - CodeSystemLocalObservationsCodesVitalRecords

  RaceEthnicityValueSets:
    name: Race and Ethnicity ValueSets
    resources:  
      - ValueSetCodedRaceAndEthnicityPersonVitalRecords
      #- ValueSetHispanicNoUnknownVitalRecords
      - ValueSetHispanicOriginVitalRecords
      - ValueSetInputRaceAndEthnicityPersonVitalRecords
      - ValueSetRaceCodeVitalRecords

  AddressValueSets:
    name: Address ValueSets
    resources:  
      - ValueSetBirthplaceCountryVitalRecords
      - ValueSetJurisdictionVitalRecords
      - ValueSetResidenceCountryVitalRecords
      - ValueSetStatesTerritoriesAndProvincesVitalRecords
      - ValueSetUSStatesAndTerritoriesVitalRecords
      - ValueSetUSStatesVitalRecords
      - ValueSetUSTerritoriesVitalRecords

  OtherValueSets:
    name: Other ValueSets
    resources:  
      - ValueSetBirthAttendantTitlesVitalRecords
      - ValueSetSexAssignedAtBirthVitalRecords
      - ValueSetEducationLevelVitalRecords
      - ValueSetEducationLevelPersonVitalRecords
      - ValueSetFatherRelationshipVitalRecords
      - ValueSetMaritalStatusVitalRecords
      - ValueSetMotherRelationshipVitalRecords
      - ValueSetRoleVitalRecords 
      - ValueSetUnitsOfAgeVitalRecords
      - ValueSetYesNoNotApplicableVitalRecords
      - ValueSetYesNoUnknownVitalRecords
      - ValueSetYesNoUnknownNotApplicableVitalRecords
  EditFlagValueSets:
    name: ValueSets
    resources:  
      - ValueSetEditBypass01234VitalRecords
      - ValueSetDateOfBirthEditFlagsVitalRecords
      - ValueSetPluralityEditFlagsVitalRecords
  VRCLConceptMaps:
    name: Concept Maps
    resources:
      - ConceptMapBirthAttendantTitlesVitalRecords
      - ConceptMapBirthSexChildVitalRecords
      - ConceptMapBirthSexFetusVitalRecords
      - ConceptMapEditBypass01234VitalRecords
      - ConceptMapEducationLevelVitalRecords
      - ConceptMapHispanicNoUnknownVitalRecords
      - ConceptMapHispanicOriginVitalRecords
      - ConceptMapMaritalStatusVitalRecords
      - ConceptMapDateOfBirthEditFlagsVitalRecords
      - ConceptMapPluralityEditFlagsVitalRecords
      - ConceptMapRaceCodeVitalRecords 
      - ConceptMapRaceMissingValueReasonVitalRecords
      - ConceptMapRaceRecode40VitalRecords
      - ConceptMapUnitsOfAgeVitalRecords
      - ConceptMapYesNoNotApplicableVitalRecords
      - ConceptMapYesNoUnknownNotApplicableVitalRecords
      - ConceptMapYesNoUnknownVitalRecords
  VRCLParameters:
    name: Parameters
    resources:
      - expansion-parameters-vr-common

  VRCLExamples:
    name: Examples
    resources:
      - bundle-examples-of-identifiers
      - observation-input-race-and-ethnicity-vr-mother 
      - observation-input-race-and-ethnicity-vr-father 
      - observation-coded-race-and-ethnicity-vr-mother 
      - observation-coded-race-and-ethnicity-vr-father 
      - observation-autopsy-performed-indicator-vr-a-freeman
      - observation-education-level-vr-a-freeman
      - observation-emerging-issues-vr-a-freeman
      - observation-partial-date-time-example
      - observation-usual-work-vr-jada-ann-quinn-common
      - patient-child-vr-babyg-quinn-common
      - patient-child-vr-babyg-quinn-common-1
      - patient-child-vr-babyg-quinn-common-2
      - patient-child-vr-babyg-quinn-w-edit
      - patient-fetal-death-example
      - patient-mother-vr-birth-date-part-absent
      - patient-mother-vr-jada-ann-quinn-common
      - practitioner-vr-janet-seito-common
      - relatedperson-father-natural-vr-james-brandon-quinn-common
      - relatedperson-father-vr-tom-yan-lee-common
      - relatedperson-father-vr-tony-lewis-common
      - relatedperson-mother-vr-carol-hoffer-common
      - relatedperson-parent-vr-stepmother
      - us-core-patient-vr-a-freeman
      - us-core-patient-vr-unknown-name
  


#
# The ImplementationGuide resource defines several other properties
# not represented above. These properties can be used as-is and
# should follow the format defined in ImplementationGuide:
# * date
# * meta
# * implicitRules
# * language
# * text
# * contained
# * extension
# * modifierExtension
# * experimental
# * useContext
# * copyright
# * packageId
#
#
# ╭──────────────────────────────────────────SUSHI flags───────────────────────────────────────────╮
# │  The flags below configure aspects of how SUSHI processes FSH.                                 │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# The FSHOnly flag indicates if only FSH resources should be exported.
# If set to true, no IG related content will be generated.
# The default value for this property is false.
#
# FSHOnly: false
#
#
# When set to true, the "short" and "definition" field on the root element of an Extension will
# be set to the "Title" and "Description" of that Extension. Default is true.
#
# applyExtensionMetadataToRoot: true
#
#
# The instanceOptions property is used to configure certain aspects of how SUSHI processes instances.
# See the individual option definitions below for more detail.
#
instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI defaults to false for legacy reasons, manualSliceOrding is recommended for  projects.
  manualSliceOrdering: true # true | false
  # Determines for which types of Instances SUSHI will automatically set meta.profile
  # if InstanceOf references a profile:
  #
  # setMetaProfile: always # always | never | inline-only | standalone-only
  #
  #
  # Determines for which types of Instances SUSHI will automatically set id
  # if InstanceOf references a profile:
  #
  # setId: always # always | standalone-only
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pher