
ValueSet: ValueSetRaceRecode40VitalRecords
Id: ValueSet-race-recode-40-vr
Title: "ValueSet - Race Recode 40 Vital Records"
Description: "This valueset contains the set of codes used to represent NCHS Race Recode 40.

NCHS will stop delivering this coded data in this representation in 2022.

Mapping to IJE codes [here](ConceptMap-ConceptMapRaceRecode40VitalRecords.html)."
//* include codes from system CodeSystemRaceRecode40VitalRecords
* CodeSystemRaceRecode40VitalRecords#01 "White"
* CodeSystemRaceRecode40VitalRecords#02 "Black"
* CodeSystemRaceRecode40VitalRecords#03 "American Indian or Alaskan Native (AIAN)"
* CodeSystemRaceRecode40VitalRecords#04 "Asian Indian"
* CodeSystemRaceRecode40VitalRecords#05 "Chinese"
* CodeSystemRaceRecode40VitalRecords#06 "Filipino"
* CodeSystemRaceRecode40VitalRecords#07 "Japanese"
* CodeSystemRaceRecode40VitalRecords#08 "Korean"
* CodeSystemRaceRecode40VitalRecords#09 "Vietnamese"
* CodeSystemRaceRecode40VitalRecords#10 "Other or Multiple Asian"
* CodeSystemRaceRecode40VitalRecords#11 "Hawaiian"
* CodeSystemRaceRecode40VitalRecords#12 "Guamanian"
* CodeSystemRaceRecode40VitalRecords#13 "Samoan"
* CodeSystemRaceRecode40VitalRecords#14 "Other or Multiple Pacific Islander"
* CodeSystemRaceRecode40VitalRecords#15 "Black and White"
* CodeSystemRaceRecode40VitalRecords#16 "Black and AIAN"
* CodeSystemRaceRecode40VitalRecords#17 "Black and Asian"
* CodeSystemRaceRecode40VitalRecords#18 "AIAN and NHOPI"
* CodeSystemRaceRecode40VitalRecords#19 "NHOPI and White"
* CodeSystemRaceRecode40VitalRecords#20 "AIAN and Asian"
* CodeSystemRaceRecode40VitalRecords#21 "AIAN and NHOPI-2"
* CodeSystemRaceRecode40VitalRecords#22 "Asian and White"
* CodeSystemRaceRecode40VitalRecords#23 "Asian and NHOPI"
* CodeSystemRaceRecode40VitalRecords#24 "NHOPI and White-2"
* CodeSystemRaceRecode40VitalRecords#25 "Black, AIAN and White"
* CodeSystemRaceRecode40VitalRecords#26 "Black, AIAN and Asian"
* CodeSystemRaceRecode40VitalRecords#27 "Black, AIAN and NHOPI"
* CodeSystemRaceRecode40VitalRecords#28 "Black, Asian and White"
* CodeSystemRaceRecode40VitalRecords#29 "Black, Asian and NHOPI"
* CodeSystemRaceRecode40VitalRecords#30 "Black, NHOPI and White"
* CodeSystemRaceRecode40VitalRecords#31 "AIAN, Asian and White"
* CodeSystemRaceRecode40VitalRecords#32 "AIAN, NHOPI and White"
* CodeSystemRaceRecode40VitalRecords#33 "AIAN, Asian and NHOPI"
* CodeSystemRaceRecode40VitalRecords#34 "Asian, NHOPI and White"
* CodeSystemRaceRecode40VitalRecords#35 "Black, AIAN, Asian and White"
* CodeSystemRaceRecode40VitalRecords#36 "Black, AIAN, Asian and NHOPI"
* CodeSystemRaceRecode40VitalRecords#37 "Black, AIAN, NHOPI and White"
* CodeSystemRaceRecode40VitalRecords#38 "Black, Asian, NHOPI and White"
* CodeSystemRaceRecode40VitalRecords#39 "AIAN, Asian, NHOPI and White"
* CodeSystemRaceRecode40VitalRecords#40 "Black, AIAN, Asian, NHOPI and White"
* CodeSystemRaceRecode40VitalRecords#99 "Unknown and Other Race"
* ^experimental = false