ValueSet: ValueSetHispanicOriginVitalRecords
Id: ValueSet-hispanic-origin-vr
Title: "ValueSet - HispanicOrigin Vital Records"
Description: "This valueset contains the set of codes used to represent NCHS HispanicOrigin.


Mapping to IJE codes [here](ConceptMap-ConceptMapHispanicOriginVitalRecords.html)."
//* include codes from system CodeSystemHispanicOriginVitalRecords
* CodeSystemHispanicOriginVitalRecords#100 "Non-Hispanic"
* CodeSystemHispanicOriginVitalRecords#200 "Spaniard"
* CodeSystemHispanicOriginVitalRecords#201 "Andalusian"
* CodeSystemHispanicOriginVitalRecords#202 "Asturian"
* CodeSystemHispanicOriginVitalRecords#203 "Castillian"
* CodeSystemHispanicOriginVitalRecords#204 "Catalonian"
* CodeSystemHispanicOriginVitalRecords#205 "Balearic Islander"
* CodeSystemHispanicOriginVitalRecords#206 "Gallego"
* CodeSystemHispanicOriginVitalRecords#207 "Valencian"
* CodeSystemHispanicOriginVitalRecords#208 "Canarian"
* CodeSystemHispanicOriginVitalRecords#209 "Spanish Basque"
* CodeSystemHispanicOriginVitalRecords#210 "Mexican Checkbox"
* CodeSystemHispanicOriginVitalRecords#211 "Mexican"
* CodeSystemHispanicOriginVitalRecords#212 "Mexican American"
* CodeSystemHispanicOriginVitalRecords#213 "Mexicano"
* CodeSystemHispanicOriginVitalRecords#214 "Chicano"
* CodeSystemHispanicOriginVitalRecords#215 "La Raza"
* CodeSystemHispanicOriginVitalRecords#216 "Mexican American Indian"
* CodeSystemHispanicOriginVitalRecords#217 "Caribbean (Reassigned to 290)"
* CodeSystemHispanicOriginVitalRecords#218 "Mexico"
* CodeSystemHispanicOriginVitalRecords#220 "Central and South America"
* CodeSystemHispanicOriginVitalRecords#221 "Costa Rican"
* CodeSystemHispanicOriginVitalRecords#222 "Guatemalan"
* CodeSystemHispanicOriginVitalRecords#223 "Honduran"
* CodeSystemHispanicOriginVitalRecords#224 "Nicaraguan"
* CodeSystemHispanicOriginVitalRecords#225 "Panamanian"
* CodeSystemHispanicOriginVitalRecords#226 "Salvadoran"
* CodeSystemHispanicOriginVitalRecords#227 "Central American"
* CodeSystemHispanicOriginVitalRecords#228 "Central American Indian"
* CodeSystemHispanicOriginVitalRecords#229 "Canal Zone"
* CodeSystemHispanicOriginVitalRecords#231 "Argentinean"
* CodeSystemHispanicOriginVitalRecords#232 "Bolivian"
* CodeSystemHispanicOriginVitalRecords#233 "Chilean"
* CodeSystemHispanicOriginVitalRecords#234 "Colombian"
* CodeSystemHispanicOriginVitalRecords#235 "Ecuadorian"
* CodeSystemHispanicOriginVitalRecords#236 "Paraguayan"
* CodeSystemHispanicOriginVitalRecords#237 "Peruvian"
* CodeSystemHispanicOriginVitalRecords#238 "Uruguayan"
* CodeSystemHispanicOriginVitalRecords#239 "Venezuelan"
* CodeSystemHispanicOriginVitalRecords#240 "South American Indian"
* CodeSystemHispanicOriginVitalRecords#241 "Criollo"
* CodeSystemHispanicOriginVitalRecords#242 "South American"
* CodeSystemHispanicOriginVitalRecords#250 "Latin American"
* CodeSystemHispanicOriginVitalRecords#251 "Latin"
* CodeSystemHispanicOriginVitalRecords#252 "Latino"
* CodeSystemHispanicOriginVitalRecords#260 "Puerto Rican Checkbox"
* CodeSystemHispanicOriginVitalRecords#261 "Puerto Rican"
* CodeSystemHispanicOriginVitalRecords#270 "Cuban Checkbox"
* CodeSystemHispanicOriginVitalRecords#271 "Cuban"
* CodeSystemHispanicOriginVitalRecords#275 "Dominican"
* CodeSystemHispanicOriginVitalRecords#280 "Other Spanish Checkbox"
* CodeSystemHispanicOriginVitalRecords#281 "Hispanic"
* CodeSystemHispanicOriginVitalRecords#282 "Spanish"
* CodeSystemHispanicOriginVitalRecords#283 "Californio"
* CodeSystemHispanicOriginVitalRecords#284 "Tejano"
* CodeSystemHispanicOriginVitalRecords#285 "Nuevo Mexicano"
* CodeSystemHispanicOriginVitalRecords#286 "Spanish American"
* CodeSystemHispanicOriginVitalRecords#287 "Spanish American Indian"
* CodeSystemHispanicOriginVitalRecords#288 "Meso American Indian"
* CodeSystemHispanicOriginVitalRecords#289 "Mestizo"
* CodeSystemHispanicOriginVitalRecords#290 "Caribbean"
* CodeSystemHispanicOriginVitalRecords#291 "Multiple Hispanic Responses"
* CodeSystemHispanicOriginVitalRecords#299 "Other Spanish"
* CodeSystemHispanicOriginVitalRecords#996 "Uncodable"
* CodeSystemHispanicOriginVitalRecords#997 "Deferred"
* CodeSystemHispanicOriginVitalRecords#998 "Unknown"
* CodeSystemHispanicOriginVitalRecords#999 "First Pass Reject"
* ^experimental = false